version: "{build}"
clone_folder: "c:/WORK"

environment:
  global:
    CABOPTS: "--store-dir=c:/SR --http-transport=plain-http"
    C_INCLUDE_PATH: "c:/msys64/mingw64/include"
    LIBRARY_PATH: "c:/msys64/mingw64/lib;c:/msys64/mingw64/bin"
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
  matrix:
    - GHCVER: "8.4.3"
    - GHCVER: "8.2.2"
    - GHCVER: "8.0.2"
    - GHCVER: "7.10.3.2"
    - GHCVER: "7.8.4.1"
    - GHCVER: "7.6.3.1"

cache:
 - "c:/SR"

install:
 - "choco install -y cabal"
 - "choco install -y ghc --version %GHCVER%"
 - "refreshenv"
 - "set PATH=C:\\msys64\\mingw64\\bin;C:\\msys64\\usr\\bin;%PATH%;C:\\ghc\\ghc-%GHCVERSION%\\bin"
 - "cabal --version"
 - "ghc --version"
 - "cabal %CABOPTS% update -vverbose+nowrap"

build: off

test_script:
 - IF EXIST configure.ac bash -c "autoreconf -i"
 - "cabal %CABOPTS% new-build -vnormal+nowrap --dry all"
 - ps: "Push-AppveyorArtifact dist-newstyle\\cache\\plan.json"
 - "cabal %CABOPTS% new-build -j -vnormal+nowrap all --dep"
 - "cabal %CABOPTS% new-build -j1 -vnormal+nowrap all"
 - "cabal %CABOPTS% new-test -j1 -vnormal+nowrap all"
