language: c
sudo: false

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

matrix:
  include:
  - env: BUILD=cabal GHCVER=7.2.1 CABALVER=1.16
    compiler: ": #GHC 7.2.1"
    addons: {apt: {packages: [cabal-install-1.16,ghc-7.2.1], sources: [hvr-ghc]}}
  - env: BUILD=cabal GHCVER=7.2.2 CABALVER=1.16
    compiler: ": #GHC 7.2.2"
    addons: {apt: {packages: [cabal-install-1.16,ghc-7.2.2], sources: [hvr-ghc]}}
  - env: BUILD=cabal GHCVER=7.4.2 CABALVER=1.16
    compiler: ": #GHC 7.4.2"
    addons: {apt: {packages: [cabal-install-1.16,ghc-7.4.2], sources: [hvr-ghc]}}
  # we have to use CABALVER=1.16 for GHC<7.6 as well, as there's
  # no package for earlier cabal versions in the PPA
  - env: BUILD=cabal GHCVER=7.6.3 CABALVER=1.16
    compiler: ": #GHC 7.6.3"
    addons: {apt: {packages: [cabal-install-1.16,ghc-7.6.3], sources: [hvr-ghc]}}
  - env: BUILD=cabal GHCVER=7.8.4 CABALVER=1.18
    compiler: ": #GHC 7.8.4"
    addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4], sources: [hvr-ghc]}}
  - env: BUILD=cabal GHCVER=7.10.1 CABALVER=1.22
    compiler: ": #GHC 7.10.1"
    addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.1], sources: [hvr-ghc]}}
  - env: BUILD=cabal GHCVER=7.10.2 CABALVER=1.22
    compiler: ": #GHC 7.10.2"
    addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2], sources: [hvr-ghc]}}
  - env: BUILD=cabal GHCVER=7.10.3 CABALVER=1.22
    compiler: ": #GHC 7.10.3"
    addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3], sources: [hvr-ghc]}}

  - env: BUILD=stack LTS_HASKELL_VER=2.22
    compiler: ": #stack lts-2.22"

  - env: BUILD=stack LTS_HASKELL_VER=5.14
    compiler: ": #stack lts-5.14"

  - env: BUILD=stack LTS_HASKELL_VER=2.22
    compiler: ": #stack lts-2.22 osx"
    os: osx

  - env: BUILD=stack LTS_HASKELL_VER=5.14
    compiler: ": #stack lts-5.14 osx"
    os: osx

  - env: BUILD=cabal GHCVER=head  CABALVER=head
    addons: {apt: {packages: [cabal-install-head,ghc-head], sources: [hvr-ghc]}}

  allow_failures:
  - env: BUILD=cabal GHCVER=head  CABALVER=head
  - env: BUILD=stack LTS_HASKELL_VER=2.22

before_install:
 - unset CC
 - case "$BUILD" in
     stack)
       export PATH=$HOME/.local/bin:$PATH;;
     cabal)
       export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:$PATH;;
   esac
 - mkdir -p ~/.local/bin
 - if [ `uname` = "Darwin" ];
   then
     curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin;
   else
     curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack';
   fi

install:
 - autoreconf -i
 - |
   case "$BUILD" in
     stack)
       echo "resolver: lts-$LTS_HASKELL_VER" > stack.yaml;
       stack --no-terminal --install-ghc test --only-dependencies;;
     cabal)
       echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]";
       cabal --version;
       travis_retry cabal update;
       rm -f $(stack path --dist-dir)/stack-*.tar.gz;
       stack sdist --pvp-bounds=both;
       tar xf $(stack path --dist-dir)/stack-*.tar.gz --wildcards --strip-components=1 '*/stack.cabal';
       cabal install --only-dependencies --enable-tests --enable-benchmarks --force-reinstalls --ghc-options=-O0;;
   esac

script:
 - case "$BUILD" in
     stack)
       stack --no-terminal test --haddock --no-haddock-deps;;
     cabal)
       cabal configure --enable-tests --enable-benchmarks -v2 --ghc-options="-O0 -Werror";
       cabal build;
       cabal check || [ "$CABALVER" == "1.16" ];
       true Using cabal test was giving trouble with cabal 1.22;
       ./dist/build/test/test;
       cabal sdist;
       cabal copy;
       SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz &&
       (cd dist && cabal install --force-reinstalls "$SRC_TGZ");;
   esac
